name: "Microsoft Defender For Devops"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 2 * * 2'

jobs:
  MSDO:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: ${{ runner.os }}-nuget-

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x

    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1.6.0
      id: msdo

    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}

    - name: Notify Slack on build success
      if: success()
      uses: slackapi/slack-github-action@v1.25.0
      with:
        payload: '{"text":"Build completed successfully!"}'
        channel: '#alerts'
        token: ${{ secrets.SLACK_BOT_TOKEN }}

    - name: Notify Slack on build failure
      if: failure()
      uses: slackapi/slack-github-action@v1.25.0
      with:
        payload: '{"text":"Build failed!"}'
        channel: '#alerts'
        token: ${{ secrets.SLACK_BOT_TOKEN }}
