- name: Run Python Actions
  uses: microsoft/action-python@0.7.2
  with:
    root: '.'
    toml: 'pyproject.toml'
    python_version: ${{ matrix.python-version }}
    black: true
    bandit: true
    pylint: true
    pyright: true
    flake8: true
    mypy: true
    pytest: true
    pypi_publish: false
    args: ''
    pypi_repo: 'pypi'
    pypi_password: ${{ secrets.PYPI_PASSWORD }}
    version_suffix: '-dev-${{ github.run_number }}'
    github_token: ${{ secrets.GITHUB_TOKEN }}
    workdir: 'src'
    testdir: 'tests'
    coverage: true
    flags: 'unittests'
    level: 'error'
    reporter: 'github-pr-check'
    filter_mode: 'added'
    fail_on_error: false
    reviewdog_flags: ''
